### PR TITLE
Show a loading animation on login button during login

### PR DESCRIPTION
**Pull request by myxmaster**
Use [view-design button](https://www.iviewui.com/components/button-en#Loading) instead of default html button to be able to show a loading indicator during login. Also added a hover effect. This addresses #926.

grafik

### CODE REVIEW

**Review by Peersyst — APPROVED** [review]
Nice work!

**Comment by bassemmagdy** [comment]
@myxmaster great work! can you rebase all your pull requests to integration branch?

**Comment by myxmaster** [comment]
Thanks. Yes, will do.

Do you want pull requests targeting integration in general? I ask because your [doc ](https://github.com/nemgrouplimited/symbol-desktop-wallet/blob/main/CONTRIBUTING.md)says this: "Push your local changes to your forked copy of the repository and submit a pull request targeting the master branch."

**Comment by bassemmagdy** [comment]
> Thanks. Yes, will do.
> 
> Do you want pull requests targeting integration in general? I ask because your [doc ](https://github.com/nemgrouplimited/symbol-desktop-wallet/blob/main/CONTRIBUTING.md)says this: "Push your local changes to your forked copy of the repository and submit a pull request targeting the master branch."

Yes, we're now using the main branch only for releases but during the development phase we're always targeting integration branch in our pull requests.

**Comment by myxmaster** [comment]
I changed the target branch of all my PRs to integration. Is that sufficient or will I have to rebase my feature branches as well?

**Comment by myxmaster** [comment]
I found out that by pressing enter multiple times, login process was triggered repeatedly (in parallel). Now preventing this by checking if login process is already running.

**Review by rg911 — APPROVED** [review]

**Pull request merged**
