### PR TITLE
Application can be used without accepting terms and conditions #946

### PR DESCRIPTION
**Pull request by james-lin71**

### CODE REVIEW

**Review by rg911 — CHANGES_REQUESTED** [review]
why create the terms in the wallet modal? These supposed to be an external link controlled by the legal and marketing team

**Comment by james-lin71** [comment]
Oh, I didn't care about  for legal and marketing team, will make change to be support with external link.

**Review by rg911 — COMMENTED** [review]
@bassemmagdy @OlegMakarenko 

I believe this has been fixed already by @OlegMakarenko ?

**Comment by james-lin71** [comment]
There were additional exception that users can navigate to the some other pages like 'namespaces', 'mosaic' and etc.
The terms & conditions accept modal was restricting user only on home page that shows transactions history.
So, some suggestion was moving the terms & conditions accept logic to the create/import profile logic, and I integrated this on finalize of create/import profile page to make sure users must accept terms and conditions before their use.

**Review by bassemmagdy — APPROVED** [review]

**Review by rg911 — APPROVED** [review]

**Pull request merged**
