### PR TITLE
fix local issue in amount field

### LINKED ISSUE #1531: Depending on the device's locale, amount input doesn't accept decimal comma or dot.
After testing the latest version, the team found a defect where depending on the locale being used, the amount input rejects the standard decimal comma/point.

For example, in most European countries you would write "1.000,00" and in other countries you would write "1,000.00", both to represent "one thousand".

### PR DESCRIPTION
**Pull request by bassemmagdy**
fixes  #1531

### CODE REVIEW

**Comment by AnthonyLaw** [comment]
It seems not right.

give `123,321` it shows `123.321`

Screenshot 2021-06-22 at 11 37 37 PM

Screenshot 2021-06-22 at 11 37 33 PM

**Comment by bassemmagdy** [comment]
@AnthonyLaw what does your locale uses for decimal separator?

**Review by AdriaCarrera — APPROVED** [review]

**Comment by AnthonyLaw** [comment]
@cryptoBeliever can you help test with this?
My desktop setting.

Screenshot 2021-06-28 at 7 28 51 PM

Screenshot 2021-06-28 at 7 29 44 PM

**Comment by cryptoBeliever** [comment]
@AnthonyLaw @bassemmagdy 
I'm using language PL. Problem is not fixed:

image
image

**Review by AnthonyLaw — APPROVED** [review]

**Pull request merged**
