### PR TITLE
Separate HD Wallets from Private Key wallets

### LINKED ISSUE #221: Separate HD Wallets from Private Key wallets
Import account page:
- Add a link around "more options are being worked on" to import a private key

Account creation:
- It should be possible to create a profile with a private key

Wallets import
- When using an HD profile, it should not be possible to import a private key
- When using a private key profile, it should not be possible to import a private key nor a wallet

### PR DESCRIPTION
**Pull request by vincent-lee90**
This is the previous PR, but I rebased it and added unit test ( fixes #221 )

### CODE REVIEW

**Comment by fullcircle23** [comment]
Hi @vincent-lee90
Found a bug. Login using a private key profile name gets redirected to Mnemonic Passphrase Setup page. This behaviour is incorrect as the Mnemonic passphrase is for the HD Wallet only. Private Key wallet do not use Mnemonic passphrase.

Steps to reproduce:
1. Create a new profile.
2. Import an existing account private key.
3. Logout.
4. Login using the newly created private key profile.
5. Redirected to mnemonic passphrase setup page.

Console log:
```
 (11/06/2020, 19:44:39) [DEBUG] Changing current profile to mypkprofile2
 (11/06/2020, 19:44:39) [DEBUG] Using profile settings mypkprofile2,en-US,1,,http://explorer-951.symboldev.network
 (11/06/2020, 19:44:39) [INFO] Notification (Success): successful_operation
 (11/06/2020, 19:44:48) [DEBUG] Adding account to profile: mypkprofile2 with: TCRB45H6YMVC6XK5OA7UIZYIGRO5VSZQQACNKAYV
 (11/06/2020, 19:44:48) [DEBUG] Changing current profile to mypkprofile2
 (11/06/2020, 19:44:48) [DEBUG] Using profile settings mypkprofile2,en-US,1,,http://explorer-951.symboldev.network
 (11/06/2020, 19:44:48) [DEBUG] Changing current profile to mypkprofile2
 (11/06/2020, 19:44:48) [DEBUG] Using profile settings mypkprofile2,en-US,1,,http://explorer-951.symboldev.network
 (11/06/2020, 19:44:48) [DEBUG] Store action account/SET_CURRENT_ACCOUNT dispatched with TCRB45H6YMVC6XK5OA7UIZYIGRO5VSZQQACNKAYV
 (11/06/2020, 19:44:48) [DEBUG] Store action account/SET_CURRENT_SIGNER dispatched with TCRB45H6YMVC6XK5OA7UIZYIGRO5VSZQQACNKAYV
 (11/06/2020, 19:44:48) [DEBUG] Opening REST websocket channel connections with TCRB45H6YMVC6XK5OA7UIZYIGRO5VSZQQACNKAYV
 (11/06/2020, 19:44:48) [INFO] Notification (Success): successful_operation
 (11/06/2020, 19:44:48) [DEBUG] Profile login successful with profileName: mypkprofile2
 (11/06/2020, 19:45:01) [DEBUG] Store action account/RESET_CURRENT_ACCOUNT dispatched
 (11/06/2020, 19:45:27) [DEBUG] Changing current profile to mypkprofile2
 (11/06/2020, 19:45:27) [DEBUG] Using profile settings mypkprofile2,en-US,1,,http://explorer-951.symboldev.network
 (11/06/2020, 19:45:27) [WARNING] Profile has not setup mnemonic pass phrase, redirecting: mypkprofile2
```

**Comment by vincent-lee90** [comment]
@fullcircle23  
 thanks your review.

**Comment by vincent-lee90** [comment]
@fullcircle23 
you said "On page "importPrivateKey/input", display the Network type input value." 
I don't follow this. 
Isn't that what I did now?
image

**Comment by fullcircle23** [comment]
@vincent-lee90 The Network type should be pre-filled since it is already known from the previous step. I've DM you on slack.

**Comment by fullcircle23** [comment]
@vincent-lee90 
As discussed:
- The Network type in the "Enter your private key" form is pre-filled. 
- If the network type does not match, then display both the pre-filled value and the actual network type for the private key.
- The actual network type must be in **red** colour to distinguish it from the pre-filled value.
- A warning message something like `Actual network type does not match your input` must appear beside it.
- User must be able go back to the previous form to enter a different private key or cancel the import altogether.

**Comment by vincent-lee90** [comment]
> @vincent-lee90
> As discussed:
> 
> * The Network type in the "Enter your private key" form is pre-filled.
> * If the network type does not match, then display both the pre-filled value and the actual network type for the private key.
> * The actual network type must be in **red** colour to distinguish it from the pre-filled value.
> * A warning message something like `Actual network type does not match your input` must appear beside it.
> * User must be able go back to the previous form to enter a different private key or cancel the import altogether.

confirmed

**Comment by fullcircle23** [comment]
@vincent-lee90 

Slight change:

- The Network type in the "Enter your private key" form is pre-filled. 
- If the network type does not match, then display both the pre-filled value and the actual network type for the private key.
```
    Network:  TEST_NET         FOUND: MAIN_NET    Warning: Actual network type does not match your input
```
- The actual network type and warning message must be in **red** colour to distinguish it from the pre-filled value and alert user.
- User must be able go back to the previous form to enter a different private key or cancel the import altogether.

@evias please review the above proposed changes.

**Comment by vincent-lee90** [comment]
> @vincent-lee90 Unfortunately this branch and the master branch has diverged hence it's not possible to review/test this change. Please resolve the merge conflicts.

Thanks for reminding me, and I've done it

**Comment by vincent-lee90** [comment]
> @vincent-lee90
> The private key wallet dashboard:
> image
> 
> is not looking the same as the mnemonic wallet dashboard:
> image
> 
> git rebase origin shows your PR branch is up to date with master:
> 
> ```
> $ git rebase origin  
> Current branch pr/396 is up to date.
> ```
> 
> Please check the differences in the 2 screens on your side. The 2nd screen (includes Harvesting) is the correct one; it is the current one in master.

I can't reproduce these what you said on my side.
would you mind to delete the branch in your local and re-pull it?

**Comment by fullcircle23** [comment]
I actually got the above results after deleting and re-pull. But let me
re-clone the repo and try again after GitHub is back up. GitHub is still
down at this moment https://twitter.com/githubstatus

**Comment by fullcircle23** [comment]
@vincent-lee90 I did a fresh clone, checked-out this PR branch, did `git rebase origin` and still getting the same result. 

image

When I login using an HD profile, I see this at the top (correct):

image

When I login using a private key profile, I see this at the top (incorrect - instead of Harvesting, it's showing Speed):

image

**Comment by vincent-lee90** [comment]
> git rebase origin

I guess you don't need to type `git rebase origin`(i'm not sure)

**Comment by evias** [comment]
@fullcircle23 the fact that harvesting is not enabled for Private Key profiles is intentional because we don't have a mechanism to store remote account information for now.

If it needs a rebase, it always _against master_, nothing else :+1: 

@bassemmagdy, Please have a few tests done with this PR :v:

**Comment by fullcircle23** [comment]
@evias Thanks for the explanation.. could you please clarify "we don't have a mechanism to store remote account information for now". Thanks in advance.

**Pull request closed without merging**
