### PR TITLE
Several address handling fixes

### PR DESCRIPTION
**Pull request by myxmaster**
- Now copying pretty account address to clipboard instead of plain
- Removed spaces before and after the address in account details
- Now saving contact addresses as plain and therefore preventing creation of duplicate contacts
- Always display pretty contact addresses instead of saved one

### CODE REVIEW

**Comment by myxmaster** [comment]
@cryptoBeliever told me that most exchanges don't work with pretty addresses (with hyphens), so I guess the first point (_Now copying pretty account address to clipboard instead of plain_) should not be done.

**Comment by rg911** [comment]
> @cryptoBeliever told me that most exchanges don't work with pretty addresses (with hyphens), so I guess the first point (_Now copying pretty account address to clipboard instead of plain_) should not be done.
> 
> On the other hand we **do** work with pretty addresses (for good reasons!). So users could get the pretty addresses from other places (if they don't use the copy-button) and then they still have this problem with the exchange... It could be extra confusing if they sometimes get the pretty address and sometimes the plain address.

The pretty format is for displaying only. All address operation should be `plain`. Buth 'pretty' helps when 2 addresses come with similar strings. Personally I would prefer showing pretty (with copying the plain format). It is the same as NIS1 nano wallet. 
@cryptoBeliever @bassemmagdy @AdriaCarrera ?

**Comment by cryptoBeliever** [comment]
> > @cryptoBeliever told me that most exchanges don't work with pretty addresses (with hyphens), so I guess the first point (_Now copying pretty account address to clipboard instead of plain_) should not be done.
> > On the other hand we **do** work with pretty addresses (for good reasons!). So users could get the pretty addresses from other places (if they don't use the copy-button) and then they still have this problem with the exchange... It could be extra confusing if they sometimes get the pretty address and sometimes the plain address.
> 
> The pretty format is for displaying only. All address operations should be `plain`. But 'pretty' help when 2 addresses come with similar strings. Personally, I would prefer showing pretty (with copying the plain format). It is the same as NIS1 nano wallet.
> @cryptoBeliever @bassemmagdy @AdriaCarrera ?

@rg911 yes showing pretty and copying plain format is fine for me. In NIS1 it work in this way (if user using copy button)

**Comment by myxmaster** [comment]
Alright, you convinced me.

**Review by rg911 — APPROVED** [review]

**Comment by rg911** [comment]
@myxmaster  any chance you could have a look at the conflicts?

**Comment by myxmaster** [comment]
Conflicts resolved

**Review by rg911 — APPROVED** [review]

**Pull request merged**
