### PR TITLE
 suggestions for profile creation

### PR DESCRIPTION
**Pull request by OlegLialin**
Rephrased profile creation

### CODE REVIEW

**Comment by surekabpm** [comment]
Hi, I tried to run the code and test the functionality, I'm getting this error while extracting the files
image

I skipped them to extract the entire files but while running the npm run dev code I'm getting error. pls suggest how to go forward 
image

**Comment by OlegLialin** [comment]
Hi, did you do npm install?

ср, 31 мар. 2021 г. в 14:48, surekabpm ***@***.***>:

**Comment by surekabpm** [comment]
yes .. i did npm install

**Comment by OlegLialin** [comment]
Unfortunately, I have no idea what went wrong. Locally everything works
fine for me

ср, 31 мар. 2021 г. в 15:04, surekabpm ***@***.***>:

**Comment by bassemmagdy** [comment]
fixed [here](https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/1512)

**Pull request closed without merging**
